name: Deploy VitePress to GitHub Pages

on:
  push:
    branches: [main] # Se ejecutará cuando hagas un push a la branch main
  workflow_dispatch: # Permite ejecutarlo manualmente desde GitHub Actions

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Necesario si usas lastUpdated en VitePress

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.17.1
          cache: pnpm # Usa pnpm en lugar de npm

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9 # Asegúrate de usar la versión correcta de pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile # Instala dependencias con pnpm

      - name: Build with VitePress
        run: |
          pnpm run docs:build
          touch docs/.vitepress/dist/.nojekyll # Evita problemas con archivos _ en GitHub Pages

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/.vitepress/dist # Subir los archivos generados para deploy

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
